language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
script:
 # dotnet
 - cd Game
 - dotnet restore
 - dotnet publish -c release
 # angular
 - npm install @angular/cli --global
 - cd Game
 - npm install
 - npm run lint
 - ng build -prod
notifications:
  email:
    - notSteven@fakeEmail.com